var NODES = [
    {
        "id":"1",
        "label":"Node 1",
        "group":"database",
        "x":-2652,
        "y":-246
    },
    {
        "id":"3",
        "group":"neuron",
        "x":-2455,
        "y":-478
    },
    {
        "id":"4",
        "group":"neuron",
        "x":-2619,
        "y":245
    },
    {
        "id":"5",
        "group":"neuron",
        "x":138,
        "y":-47
    },
    {
        "id":"6",
        "group":"neuron",
        "x":694,
        "y":-29
    },
    {
        "id":"7",
        "group":"neuron",
        "x":508,
        "y":105
    },
    {
        "id":"8",
        "group":"neuron",
        "x":502,
        "y":-91
    },
    {
        "id":"9",
        "label":"Hold",
        "group":"neuron",
        "x":1267,
        "y":60
    },
    {
        "id":"10",
        "group":"neuron",
        "x":358,
        "y":-153
    },
    {
        "id":"11",
        "group":"neuron",
        "x":691,
        "y":-93
    },
    {
        "id":"12",
        "label":"Buy",
        "group":"neuron",
        "x":1262,
        "y":-136
    },
    {
        "id":"13",
        "group":"neuron",
        "x":696,
        "y":104
    },
    {
        "id":"14",
        "group":"neuron",
        "x":601,
        "y":175
    },
    {
        "id":"15",
        "group":"neuron",
        "x":695,
        "y":44
    },
    {
        "id":"16",
        "group":"neuron",
        "x":500,
        "y":-157
    },
    {
        "id":"17",
        "group":"neuron",
        "x":599,
        "y":-26
    },
    {
        "id":"18",
        "group":"neuron",
        "x":355,
        "y":-27
    },
    {
        "id":"19",
        "group":"neuron",
        "x":507,
        "y":43
    },
    {
        "id":"20",
        "group":"neuron",
        "x":602,
        "y":-93
    },
    {
        "id":"21",
        "group":"neuron",
        "x":600,
        "y":44
    },
    {
        "id":"22",
        "group":"neuron",
        "x":601,
        "y":-231
    },
    {
        "id":"23",
        "group":"neuron",
        "x":358,
        "y":102
    },
    {
        "id":"24",
        "group":"neuron",
        "x":504,
        "y":-27
    },
    {
        "id":"25",
        "group":"neuron",
        "x":601,
        "y":-156
    },
    {
        "id":"26",
        "label":"Sell",
        "group":"neuron",
        "x":1284,
        "y":210
    },
    {
        "id":"27",
        "group":"neuron",
        "x":690,
        "y":-156
    },
    {
        "id":"28",
        "group":"neuron",
        "x":358,
        "y":39
    },
    {
        "id":"29",
        "group":"neuron",
        "x":357,
        "y":-90
    },
    {
        "id":"30",
        "group":"neuron",
        "x":602,
        "y":105
    },
    {
        "id":"31",
        "x":1331,
        "y":67,
        "label":"new",
        "group":"csv"
    },
    {
        "id":"32",
        "x":1329,
        "y":-11,
        "label":"new",
        "group":"csv"
    },
    {
        "id":"33",
        "x":-3011,
        "y":-45,
        "label":"API",
        "image":"https://www.interactivebrokers.com/images/2015/template/logo-ib-ibkr-txtwht.svg",
        "group":"dataAPI"
    },
    {
        "id":"34",
        "x":-2473,
        "y":-12,
        "label":"INPUT HANDLER",
        "group":"inputHandler"
    },
    {
        "id":"35",
        "group":"neuron",
        "x":800,
        "y":109
    },
    {
        "id":"36",
        "group":"neuron",
        "x":795,
        "y":43
    },
    {
        "id":"37",
        "group":"neuron",
        "x":791,
        "y":-26
    },
    {
        "id":"38",
        "group":"neuron",
        "x":788,
        "y":-97
    },
    {
        "id":"39",
        "group":"neuron",
        "x":784,
        "y":-161
    },
    {
        "id":"40",
        "group":"neuron",
        "x":778,
        "y":-230
    },
    {
        "id":"41",
        "group":"neuron",
        "x":779,
        "y":-290
    },
    {
        "id":"42",
        "group":"neuron",
        "x":804,
        "y":174
    },
    {
        "id":"43",
        "group":"neuron",
        "x":803,
        "y":250
    },
    {
        "id":"44",
        "group":"neuron",
        "x":882,
        "y":117
    },
    {
        "id":"45",
        "group":"neuron",
        "x":889,
        "y":40
    },
    {
        "id":"46",
        "group":"neuron",
        "x":882,
        "y":-30
    },
    {
        "id":"47",
        "group":"neuron",
        "x":882,
        "y":-94
    },
    {
        "id":"48",
        "group":"neuron",
        "x":885,
        "y":-231
    },
    {
        "id":"49",
        "group":"neuron",
        "x":884,
        "y":-162
    },
    {
        "id":"50",
        "group":"neuron",
        "x":976,
        "y":-306
    },
    {
        "id":"51",
        "group":"neuron",
        "x":985,
        "y":248
    },
    {
        "id":"52",
        "group":"neuron",
        "x":890,
        "y":185
    },
    {
        "id":"53",
        "group":"neuron",
        "x":986,
        "y":175
    },
    {
        "id":"54",
        "group":"neuron",
        "x":990,
        "y":109
    },
    {
        "id":"55",
        "group":"neuron",
        "x":981,
        "y":42
    },
    {
        "id":"56",
        "group":"neuron",
        "x":981,
        "y":-29
    },
    {
        "id":"57",
        "group":"neuron",
        "x":985,
        "y":-93
    },
    {
        "id":"58",
        "group":"neuron",
        "x":984,
        "y":-160
    },
    {
        "id":"59",
        "group":"neuron",
        "x":980,
        "y":-232
    },
    {
        "id":"60",
        "group":"rec",
        "size":50,
        "x":-1154,
        "y":-281,
        "rW":500,
        "rH":400
    },
    {
        "id":"61",
        "group":"con",
        "size":25,
        "x":-1357,
        "y":584,
        "conO":10,
        "conW":200
    },
    {
        "id":"62",
        "group":"con",
        "size":25,
        "x":-1443,
        "y":826,
        "conO":10,
        "conW":30
    },
    {
        "id":"63",
        "group":"con",
        "size":25,
        "x":-1054,
        "y":-467,
        "conO":50,
        "conW":100
    },
    {
        "id":"64",
        "group":"con",
        "size":25,
        "x":-1071,
        "y":-338,
        "conO":50,
        "conW":20
    },
    {
        "id":"65",
        "group":"con",
        "size":25,
        "x":-765,
        "y":-403,
        "conO":150,
        "conW":50
    },
    {
        "id":"66",
        "group":"rec",
        "size":50,
        "x":-1147,
        "y":868,
        "rW":500,
        "rH":400
    },
    {
        "id":"67",
        "group":"con",
        "size":25,
        "x":-1332,
        "y":-587,
        "conO":10,
        "conW":200
    },
    {
        "id":"68",
        "group":"con",
        "size":25,
        "x":-1418,
        "y":-320,
        "conO":10,
        "conW":30
    },
    {
        "id":"69",
        "group":"con",
        "size":25,
        "x":-1057,
        "y":665,
        "conO":50,
        "conW":100
    },
    {
        "id":"70",
        "group":"con",
        "size":25,
        "x":-1076,
        "y":782,
        "conO":50,
        "conW":20
    },
    {
        "id":"71",
        "group":"con",
        "size":25,
        "x":-771,
        "y":723,
        "conO":150,
        "conW":50
    },
    {
        "id":"72",
        "group":"rec",
        "size":50,
        "x":-1153,
        "y":-1177,
        "rW":500,
        "rH":400
    },
    {
        "id":"73",
        "group":"con",
        "size":25,
        "x":-1347,
        "y":-1491,
        "conO":10,
        "conW":200
    },
    {
        "id":"74",
        "group":"con",
        "size":25,
        "x":-1449,
        "y":-1214,
        "conO":10,
        "conW":30
    },
    {
        "id":"75",
        "group":"con",
        "size":25,
        "x":-1099,
        "y":-1320,
        "conO":50,
        "conW":100
    },
    {
        "id":"76",
        "group":"con",
        "size":25,
        "x":-1118,
        "y":-1204,
        "conO":50,
        "conW":20
    },
    {
        "id":"77",
        "group":"con",
        "size":25,
        "x":-780,
        "y":-1243,
        "conO":150,
        "conW":50
    },
    {
        "id":"78",
        "shape":"dot",
        "size":25,
        "x":-1208,
        "y":207,
        "color":{
            "background":"rgba(0,0,0,1)",
            "border":"rgba(0,0,0,1)",
            "highlight":{
                "background":"rgba(0,0,0,1)",
                "border":"rgba(0,0,0,1)"
            },
            "hover":{
                "background":"rgba(0,0,0,1)",
                "border":"rgba(0,0,0,1)"
            }
        }
    },
    {
        "id":"79",
        "shape":"dot",
        "size":25,
        "x":-1211,
        "y":289,
        "color":{
            "background":"rgba(0,0,0,1)",
            "border":"rgba(0,0,0,1)",
            "highlight":{
                "background":"rgba(0,0,0,1)",
                "border":"rgba(0,0,0,1)"
            },
            "hover":{
                "background":"rgba(0,0,0,1)",
                "border":"rgba(0,0,0,1)"
            }
        }
    },
    {
        "id":"80",
        "shape":"dot",
        "size":25,
        "x":-1216,
        "y":370,
        "color":{
            "background":"rgba(0,0,0,1)",
            "border":"rgba(0,0,0,1)",
            "highlight":{
                "background":"rgba(0,0,0,1)",
                "border":"rgba(0,0,0,1)"
            },
            "hover":{
                "background":"rgba(0,0,0,1)",
                "border":"rgba(0,0,0,1)"
            }
        }
    },
    {
        "id":"81",
        "shape":"dot",
        "size":25,
        "x":-996,
        "y":134,
        "group":"none"
    },
    {
        "id":"82",
        "group":"arrowDown",
        "size":25,
        "x":-997,
        "y":438
    }
]